const greet = [
	'ভাই',
	'শোন',
	'আচ্ছা',
	'আচ্ছা শুন',
	'অ্যাই শুনো',
	'দোস্ত',
	'bro',
	'শাহ্‌রিয়ার',
	'vai',
	'dude',
	'বন্ধু',
	'Heyy~',
	'আছো?',
	'Shahriar',
	'Shadow',
	'yaar',
	'oi',
	'Oi',
	'অ্যাই শুন!',
	'ভাই আছো?',
]

const numberInBengali = ['শূন্য', 'এক', 'দুই', 'তিন', 'চার', 'পাঁচ', 'ছয়', 'সাত', 'আট', 'নয়']
const monthInBengali = [
	'জানুয়ারী',
	'ফেব্রুয়ারী',
	'মার্চ',
	'এপ্রিল',
	'মে',
	'জুন',
	'জুলাই',
	'অগাস্ট',
	'সেপ্টেম্বর',
	'অক্টোবর',
	'নভেম্বর',
	'ডিসেম্বর',
]

const reminderGIFs = [
	'excited-anime-boy',
	'anime-boy-thumbs-up',
	'anime-boy-happy',
	'anime-boy-smile',
	'all-the-best',
	'thumbs-up',
	'anime-boy-writing',
	'anime-boy-reading',
	'anime-reading',
	'anime-boy-cheering',
	'anime-boy-clapping',
	'anime-boy-yay',
]

const reminders = [
	['শাহ্‌রিয়ার আছো নাকি?'],
	['আছো?', 'গল্প লেখার কথা মনে আছে তো? 👀'],
	['যা, গল্প লেখ! আবার ভুলে যাবি, 😒', 'পারলে at least প্লট লাইনগুলো খাতায় টুকে রাখ!'],
	['Complete the stories dear! 💛'],
	['শাহ্‌রিয়ার', 'আছো?', 'গল্প লেখো'],
	['Heyy~', 'Are you writing a new story?'],
	['কি ভাই! গল্প লিখছো নাকি?'],
	['Write that story, dude! 👊🏼'],
	['ভাই', 'আছো?', 'গল্প লেখো'],
	['All the best for writing your new story. I hope people would love to read it! 😊'],
	["Don't forget to write the story and show me! 😁"],
]

const chores = [
	['Today is a great day to check the e-mails, right?'],
	['It feels like a good day to read some e-mails! 😄'],
	['আজকে ঘরটা একটু গুছিয়ে ফেললে কেমন হয়? 😁'],
	['আজকে পড়ার টেবিলটা গুছিয়ে ফেলে আম্মুকে surprise করে দিও! ✨'],
	['ল্যাপটপে ধূল জমেছে, পারলে একটু পরিষ্কার করে ফেলো'],
	['সময় পেলে ঘরটা একটু গুছিয়ে ফেল, ঠিক আছে? 😊'],
	['আজকে পড়তে বসেছ? 😒😒'],
]

const birthdayWishes = [
	['Happy Birthday, bro! 🤗'],
	['Happy Birthday, dude!'],
	['Happy Birthday, Shah! 🥰'],
	['Heyyyyyy~ Happy Birthday! 🎉🎉🎉🎉'],
	['Happiest birthday brother! ✨'],
	['Happy Birthday, Shahriar! 😄', '🍰'],
	['🍰', 'Here, have some cake'],
	['শুভ জন্মদিন বন্ধু! 🎉'],
	['শুভ জন্মদিন 😄'],
	['Yo. Happy Birthday, Shahriar 🍰'],
	['Happy Birthday, friend 🌻'],
	['নে কেক খা!', '🎂'],
	['🍫', 'চকলেট খাবি? 😁'],
]

const cheerfulComments = [
	['Take a deep breath'],
	["It's okay dear. You are doing great!"],
	['You are doing great! ✨'],
	['You are great! 🌟'],
	['You are trying your best'],
	['you are enough'],
	['i love u'],
	['i ❤ u'],
	['you are good enough'],
	["You're on fire 🔥"],
	["Don't stress. Forgive and forget."],
	["It's okay to take breaks"],
	["It's okay to slow down a bit"],
	['It will be okay 🤗'],
	["I don't really know what you are going through right now, but believe me... things will be better over time."],
	['U good?'],
	['How are you?'],
	['I hope you are doing your best to keep things sane 😄'],
	['I know you are trying your best to keep things sane 😄'],
	['how r u?'],
	['How are you doing?'],
	['Hope you are doing well, my friend! 💛'],
	['How are you today?'],
	["Heyyy~ How're you?"],
	['Your work is awesome 🙌'],
	["it isn't u."],
	['You are doing pretty well, and I know you can do even better'],
	['You are getting better every day ✌'],
	["Don't be so hard on yourself! 😥"],
	["That's some good progress there! 😎👏"],
	['Be the most attentive person in this distracted world.'],
	['Be the most attentive person in this distracted world. I know you can do that!'],
	['Shadow', 'is this really the best you can do?'],
	['You are responsible for your happiness'],
	['You may not be the best', 'but you can give your best', 'to be one of the best! ✨'],
	['Control your emotions, please... 😟'],
	['a lot of people care about you...'],
	['Feel happy just for existing in a world full of wonders and opportunities.......'],
	['we are rooting for you!'],
	["hope you're doing well 🙂"],
	['Enjoy every moment of your life! ✨'],
	[
		'You may or may not be in the best situation right now,,,,',
		'but i know,',
		'you will overcome these barriers pretty soon! 🤗',
	],
	['You may or may not be in the best situation right now,,,,', 'but i know,', 'things will get better! 🤗'],
	['live in the moment. be present'],
	["don't wanna make ur mom proud????"],
	['think before you say, dude 😉'],
	['express gratitude for the little things,,,,', "it's the little things that matter 😄💛"],
	["It's okay dear ✨"],
	['you good?'],
	['Hang in there, buddy!'],
	["don't stress it too much 😬"],
	['take a walk'],
	['ভাই একটু রেস্ট নে'],
	['যে যা বলার বলুক!'],
	[
		'যে যা বলার বলুক,,,,',
		'তুমি জানো তোমার পথ সঠিক। আরে অন্যদেরও তো অধিকার আছে নিজের মতো করে বিচার-বিবেচনা করার, তাই না?',
	],
	[
		'যে যা বলার বলুক না! তাতে কি হইসে???',
		'তুমি তো জানো তোমার পথ সঠিক',
		'আরে ভাই অন্যদেরও তো অধিকার আছে নিজের মতো করে বিচার-বিবেচনা করার, তাই না?',
	],
	['just go outside and গায়ে একটু হাওয়া লাগিয়ে আসো'],
	['just go outside and গায়ে একটু হাওয়া লাগিয়ে আসো', 'mind refresh হয়ে যাবে 😄'],
	['একটু রেস্ট নাও, দাদা!'],
	["don't stress it too much 😓"],
	['you are ENOUGH', 'you are GOOD enough', 'AND you WILL become even better!'],
	['i hope you are trying your best to make this day a great one!'],
	['নিজের নামের অর্থ সার্থক করতে হবে দোস্ত!'],
	['learn from your miskates', '*mistakes'],
	['the worst mistake you can make by not making a miskate...', 'damn autoorrect 🤦🏼‍♂️', '*mistake'],
]

const videoComments = [
	['ভাই এইটা জোস! 😆'],
	['joss na?'],
	['joss 🔥'],
	['এটা দ্যাখ! 👀'],
	['এটা দেখো, ভালো লাগবে'],
	['এইটা দেইখো', 'ভালো লাগবে 😊'],
	['ভাই', 'এইটা দেখেন', 'মন ভালো হইয়া যাইব 😁'],
]

const quoteComments = [
	['তাই না?'],
	['Right?'],
	['ঠিক না?'],
	['কথাটা কিন্তু জোস!', 'তাই না?'],
	['তাই না রে?'],
	['তাই না, শাহ্‌রিয়ার?'],
	['Right, no?'],
	['সেই না?'],
	['সেইরকম একটা কথা!'],
	['mind blown!'],
	['ভাইরে ভাই সেইই একটা কথা! 🤩'],
	["Isn't it?"],
]

const photoCategories = ['cat', 'cats', 'birds', 'flower', 'flowers', 'sunset']
const photoComments = [
	['ভাইরে ভাই'],
	['👀'],
	['এই দেখো!'],
	['কোন কারণ নাই', 'এমনেই দিলাম!', '😄'],
	['এমনেই', '😉'],
	['কিরে ভাই?? 😲'],
	['দ্যাখ!'],
	['হুদাই আরকি!'],
	['hehe'],
	['😁'],
]

export {
	greet,
	reminders,
	reminderGIFs,
	quoteComments,
	photoComments,
	photoCategories,
	videoComments,
	chores,
	birthdayWishes,
	cheerfulComments,
	monthInBengali,
	numberInBengali,
}
