name: Send Motivation

on:
    schedule:
        - cron: '0 5 * * 3' # 11 AM, on Wednesdays

jobs:
    send_motivation:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.2
            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: NPM Install
              run: npm ci
            - name: Send Motivation
              run: node src/w-cheerup.js
              env:
                  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
                  YOUTUBE_PLAYLIST_ID: ${{ secrets.YOUTUBE_PLAYLIST_ID }}
                  TENOR_API_KEY: ${{ secrets.TENOR_API_KEY }}
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
                  UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
                  PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
                  FIREBASE_RTDB_NAME: ${{ secrets.FIREBASE_RTDB_NAME }}
                  FIREBASE_RTDB_AUTH: ${{ secrets.FIREBASE_RTDB_AUTH }}
                  FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
