name: Test on Push

on:
    push:
        branches:
            - main
        paths:
            - 'src/*.js'
            - 'src/api/*.js'

jobs:
    test_on_push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.2
            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: npm install
              run: npm ci
            - name: test everything
              run: |
                  node src/w-night.js
                  node src/w-evnt.js
                  node src/w-moment.js
                  node src/w-festival.js
                  node src/w-quote.js
                  node src/w-video.js
                  node src/w-photo.js
                  node src/w-book.js
                  node src/w-cheerup.js
                  node src/w-reminder.js
                  node src/w-chore.js
                  node src/w-meme.js
                  node src/w-youtube.js
                  node src/w-bday.js
              env:
                  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
                  YOUTUBE_PLAYLIST_ID: ${{ secrets.YOUTUBE_PLAYLIST_ID }}
                  TENOR_API_KEY: ${{ secrets.TENOR_API_KEY }}
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TESTBOT_TOKEN }}
                  TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
                  UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
                  PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
                  FIREBASE_RTDB_NAME: ${{ secrets.FIREBASE_RTDB_NAME }}
                  FIREBASE_RTDB_AUTH: ${{ secrets.FIREBASE_RTDB_AUTH }}
                  FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
                  TESTING_ON_PUSH: true
