name: Send Writing Reminder

on:
    schedule:
        - cron: '0 11 * * 4' # At 5 PM (Bangladesh Standard Time) on Thursday

jobs:
    send_writing_reminder:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.5.2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 17
            - name: npm install
              run: npm ci
            - name: send writing reminder
              run: node send-reminder.js
              env:
                  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
                  YOUTUBE_PLAYLIST_ID: ${{ secrets.YOUTUBE_PLAYLIST_ID }}
                  TENOR_API_KEY: ${{ secrets.TENOR_API_KEY }}
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
                  UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
