name: Send Birthday Wish

on:
    schedule:
        - cron: '0 18 24 10 *' # At 12 AM (Bangladesh Standard Time) on day-of-month 25 in October.

jobs:
    send_birthday_wish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.5.2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 17
            - name: npm install
              run: npm ci
            - name: send birthday wish
              run: node send-birthday-wish.js
              env:
                  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
                  YOUTUBE_PLAYLIST_ID: ${{ secrets.YOUTUBE_PLAYLIST_ID }}
                  TENOR_API_KEY: ${{ secrets.TENOR_API_KEY }}
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
                  UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
